name: joytel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/html/joytel || exit
            
            # Fix Git Security & Sync
            git config --global --add safe.directory /var/www/html/joytel
            git fetch origin main
            git reset --hard origin/main
            
            # Setup Bun (Sesuaikan /root/ atau /home/dev/)
            export BUN_INSTALL="/root/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            
            # Frontend
            bun install
            bun run build
            
            # Backend (PHP 8.4 Ready)
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-dev --optimize-autoloader
            
            # Laravel Ops
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            
            # Permissions
            chown -R root:www-data .
            chmod -R 775 storage bootstrap/cache